from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from .base import CapabilityContext
from ..util import ensure_dir


def _slug(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9_]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "case"


class TestCodegenCapability:
    """Generate pytest skeletons from canonical test_suite.json."""

    name = "test_codegen"

    def register(self, subparsers: argparse._SubParsersAction) -> None:  # type: ignore[name-defined]
        p = subparsers.add_parser("test-codegen", help="Generate pytest skeletons from test_suite.json")
        p.add_argument("--test-suite", required=True, help="Path to *.test_suite.json")
        p.add_argument("--out-dir", default="generated", help="Output directory")
        p.add_argument("--framework", choices=["pytest"], default="pytest")
        p.set_defaults(_cap=self.name)

    def run(self, args: argparse.Namespace, ctx: CapabilityContext) -> int:
        suite_path = Path(args.test_suite)
        if not suite_path.exists():
            print(f"Test suite not found: {suite_path}", file=sys.stderr)
            return 2

        try:
            suite = json.loads(suite_path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"Invalid JSON: {e}", file=sys.stderr)
            return 2

        if not isinstance(suite, dict):
            print("Invalid test suite format: expected JSON object", file=sys.stderr)
            return 2

        feature = suite.get("feature") or {}
        feature_id = feature.get("id") or suite_path.stem
        fid_slug = _slug(str(feature_id))

        scenarios = suite.get("scenarios") or []
        if not isinstance(scenarios, list):
            scenarios = []

        out_dir = Path(args.out_dir) / "tests"
        ensure_dir(out_dir)
        out_file = out_dir / f"test_{fid_slug}.py"

        lines: list[str] = []
        lines.append("\"\"\"Generated by doc-quality test-codegen.\n\nThis is a skeleton. Replace TODOs with real steps/asserts/mocks.\n\"\"\"")
        lines.append("")
        lines.append("import pytest")
        lines.append("")

        if not scenarios:
            lines.append(f"def test_{fid_slug}_todo():")
            lines.append("    # TODO: no scenarios in suite")
            lines.append("    assert False, 'No scenarios generated'\n")
        else:
            for idx, s in enumerate(scenarios, start=1):
                if not isinstance(s, dict):
                    continue
                sid = str(s.get("id") or f"S{idx}")
                stitle = str(s.get("title") or "")
                name = _slug(sid + "_" + stitle)
                lines.append(f"def test_{fid_slug}_{name}():")
                lines.append(f"    \"\"\"{sid}{(': ' + stitle) if stitle else ''}\"\"\"")

                pre = s.get("preconditions") or []
                if pre:
                    lines.append("    # Preconditions:")
                    for x in pre:
                        lines.append(f"    # - {x}")

                steps = s.get("steps") or []
                if steps:
                    lines.append("    # Steps:")
                    for x in steps:
                        lines.append(f"    # - {x}")

                exp = s.get("expected") or []
                if exp:
                    lines.append("    # Expected:")
                    for x in exp:
                        lines.append(f"    # - {x}")

                lines.append("    # TODO: implement")
                lines.append("    assert True")
                lines.append("")

        out_file.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote: {out_file}")
        return 0
